### PR TITLE
Update .travis.yml: add newer node versions

### PR DESCRIPTION
**Pull request by PixnBits**
should work the same, but "should" < "will" :smile:

### CODE REVIEW

**Comment by aredridel** [comment]
It's good, but should probably add the LTS and 5.x versions too. 4.0 and 4.1 aren't as interesting as 4.2 LTS and 5

**Comment by PixnBits** [comment]
First time trying `git rebase`, lemme know if that was wrong :S

**Comment by aredridel** [comment]
Nice!

**Comment by aredridel** [comment]
LGTM!

**Pull request merged**
